command = "docker ps"
run = "docker ps --format json {args}"
passthrough_args = ["--format"]

match_output = [
  { contains = "Cannot connect to the Docker daemon", output = "Docker daemon not running" },
]

[json]

[[json.extract]]
path = "$[*]"
as = "containers"

[[json.extract.fields]]
field = "Names.0"
as = "name"

[[json.extract.fields]]
field = "Image"
as = "image"

[[json.extract.fields]]
field = "Status"
as = "status"

[on_success]
output = "Containers ({containers_count}):\n{containers | each: \"  {name}: {image} ({status})\" | join: \"\\n\"}"

[on_failure]
tail = 10
